<?php
$hooks = array(
	'displayTopOne',
	'displayTopTwo',
	'displayTopThree',
	'displayTopFour',
	'displayTopFive',
	'displayHomeNovOne',
	'displayHomeNovTwo',
	'displayHomeNovThree',
	'displayHomeNovFour',
	'displayHomeNovFive',
	'displayLeftColumnNov',
	'displayRightColumnNov',
	'displayLeftProductNov',
	'displayRightProductNov',
	'displaySidebarBlogNov'
);

$hookSupport = array(
	'hookdisplayRightColumn', 
	'hookRightColumn', 	
	'hookdisplayLeftColumn',
	'hookLeftColumn',
	'hookdisplayLeftColumnProduct',
	'hookdisplayRightColumnProduct',
	'hookdisplayTopColumn',
	'hookdisplayVerticalmenu',
	'hookdisplayTop',
	'hookdisplayHome',
	'hookFooter',
	'hookdisplayCopyright',
	'hookdisplaySlideShow',
	'hookdisplayHomeSliderOne',
	'hookdisplayHomeSliderTwo',
	'hookdisplayHomeSliderThree',
	'hookdisplayHomeSliderFour',
	'hookdisplayHomeSliderFive',
	'hookdisplayHomeSliderSix',
	'hookdisplayFooterBefore',
	'hookdisplayHomeNov',
	'hookdisplayFooter'
);
?>